spring:
  cloud:
    gateway:
      routes:
        - id: user-get-users
          uri: lb://USER-SERVICE
          predicates:
            - Method=GET
            - Path=/api/users/
        - id: user-register
          uri: lb://USER-SERVICE
          predicates:
            - Method=POST
            - Path=/api/users/register
        - id: user-login
          uri: lb://USER-SERVICE
          predicates:
            - Method=POST
            - Path=/api/users/login
        - id: user-update
          uri: lb://USER-SERVICE
          predicates:
            - Method=PUT
            - Path=/api/users/{id}
        - id: user-delete
          uri: lb://USER-SERVICE
          predicates:
            - Method=DELETE
            - Path=/api/users/{id}

        - id: ticket-get-all
          uri: lb://TICKET-SERVICE
          predicates:
            - Method=GET
            - Path=/api/ticket/
        - id: ticket-get-by-id
          uri: lb://TICKET-SERVICE
          predicates:
            - Method=GET
            - Path=/api/ticket/{id}
        - id: ticket-update
          uri: lb://TICKET-SERVICE
          predicates:
            - Method=PATCH
            - Path=/api/ticket/{id}
        - id: ticket-update-items
          uri: lb://TICKET-SERVICE
          predicates:
            - Method=PUT
            - Path=/api/ticket/{id}/items
        - id: ticket-delete
          uri: lb://TICKET-SERVICE
          predicates:
            - Method=DELETE
            - Path=/api/ticket/{id}

        - id: order-get-all
          uri: lb://ORDER-SERVICE
          predicates:
            - Method=GET
            - Path=/api/order/
        - id: order-create
          uri: lb://ORDER-SERVICE
          predicates:
            - Method=POST
            - Path=/api/order/
        - id: order-update-status
          uri: lb://ORDER-SERVICE
          predicates:
            - Method=PATCH
            - Path=/api/order/{id}/status

        - id: payment-get-all
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=GET
            - Path=/api/payment/
        - id: payment-get-by-transaction-id
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=GET
            - Path=/api/payment/{transactionId}
        - id: payment-vnpay-callback
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=GET
            - Path=/api/payment/vnpay/callback
        - id: payment-vnpay-payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=GET
            - Path=/api/payment/vnpay-payment
        - id: payment-create-root
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=POST
            - Path=/api/payment/
        - id: payment-create
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=POST
            - Path=/api/payment/create
        - id: payment-refund-by-transaction-id
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=POST
            - Path=/api/payment/{transactionId}/refund
        - id: payment-refund
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Method=POST
            - Path=/api/payment/refund

server:
  port: 8080
